export { AboutSection } from "./about-section"
export { ContactSection } from "./contact-section"
export { EducationSection } from "./education-section"
export { ExperienceSection } from "./experience-section"
export { HeroSection } from "./hero-section"
export { SkillsSection } from "./skills-section"
